#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export WORKON_HOME="$HOME/dev/python"
export IDF_PATH="$HOME/esp/esp-idf"
export NPM_PACKAGES="${HOME}/.npm-packages"
export BROWSER=chromium
export RUST_BACKTRACE=1

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
