#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias venv='. .env/bin/activate'

# Customize to your needs...
if which virtualenvwrapper.sh > /dev/null 2>&1; then
    source "$(which virtualenvwrapper.sh)"
fi
# hub
if which hub > /dev/null 2>&1; then
    alias git=hub
fi

# add the pwd to the history
function zshaddhistory() {
    print -sr "${1%%$'\n'} ### ${PWD}"
    fc -p
}

