#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# personal bin
if [[ -d $HOME/bin ]]; then
	export PATH="$PATH:$HOME/bin"
fi
# rbenv
if [[ -e $(which rbenv) ]]; then
	eval "$(rbenv init -)"
fi
# hub
if [[ -e $(which hub) ]]; then
	eval "$(hub alias -s)"
fi

export VISUAL=nvim
export EDITOR="$VISUAL"
